<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430112732 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, image_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_232B318C5E237E06 ON game (name)');
        $this->addSql('CREATE TABLE match_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slot INT NOT NULL, score INT DEFAULT NULL, is_winner BOOLEAN NOT NULL, match_id INT NOT NULL, participant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5061A392ABEACD6 ON match_participant (match_id)');
        $this->addSql('CREATE INDEX IDX_E5061A399D1C3019 ON match_participant (participant_id)');
        $this->addSql('CREATE TABLE participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, seed INT DEFAULT NULL, status VARCHAR(30) NOT NULL, user_id INT NOT NULL, tournament_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D79F6B11A76ED395 ON participant (user_id)');
        $this->addSql('CREATE INDEX IDX_D79F6B1133D1A3E7 ON participant (tournament_id)');
        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, format VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL, max_participants INT NOT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organizer_id INT NOT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD5FB8D9876C4DDA ON tournament (organizer_id)');
        $this->addSql('CREATE INDEX IDX_BD5FB8D9E48FD905 ON tournament (game_id)');
        $this->addSql('CREATE TABLE tournament_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, round_number INT NOT NULL, status VARCHAR(30) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, played_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tournament_id INT NOT NULL, winner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB0D551C33D1A3E7 ON tournament_match (tournament_id)');
        $this->addSql('CREATE INDEX IDX_BB0D551C5DFCD4B8 ON tournament_match (winner_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, avatar_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE match_participant ADD CONSTRAINT FK_E5061A392ABEACD6 FOREIGN KEY (match_id) REFERENCES tournament_match (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_participant ADD CONSTRAINT FK_E5061A399D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B11A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant ADD CONSTRAINT FK_D79F6B1133D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5FB8D9876C4DDA FOREIGN KEY (organizer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5FB8D9E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament_match ADD CONSTRAINT FK_BB0D551C33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament_match ADD CONSTRAINT FK_BB0D551C5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES participant (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE match_participant DROP CONSTRAINT FK_E5061A392ABEACD6');
        $this->addSql('ALTER TABLE match_participant DROP CONSTRAINT FK_E5061A399D1C3019');
        $this->addSql('ALTER TABLE participant DROP CONSTRAINT FK_D79F6B11A76ED395');
        $this->addSql('ALTER TABLE participant DROP CONSTRAINT FK_D79F6B1133D1A3E7');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5FB8D9876C4DDA');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5FB8D9E48FD905');
        $this->addSql('ALTER TABLE tournament_match DROP CONSTRAINT FK_BB0D551C33D1A3E7');
        $this->addSql('ALTER TABLE tournament_match DROP CONSTRAINT FK_BB0D551C5DFCD4B8');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE match_participant');
        $this->addSql('DROP TABLE participant');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP TABLE tournament_match');
        $this->addSql('DROP TABLE "user"');
    }
}
